const itemCategoryMap = {
  // 🔹 Special sweets
  "agrapan": "special-sweets",
  "anjur-sweets": "special-sweets",
  "baklava": "special-sweets",
  "beshan-laddo": "special-sweets",
  "cashew-sweets": "special-sweets",
  "dry-fruit-chikki": "special-sweets",
  "jaggery-coconut-burfi": "special-sweets",
  "kaju-bite": "special-sweets",
  "oppat": "special-sweets",
  "spl-beetroot-mysurepak": "special-sweets",
  "spl-boost-burfi": "special-sweets",
  "spl-corrot-mysorepak": "special-sweets",
  "spl-dates-burfi": "special-sweets",
  "spl-dates-laddo": "special-sweets",
  "spl-horlicks-burfi": "special-sweets",
  "spl-jelabi": "special-sweets",
  "spl-lala-mysurepak": "special-sweets",
  "spl-milk-mysorepak": "special-sweets",
  "spl-moti-laddo": "special-sweets",
  "spl-mysorepak":"special-sweets",
  "spl-peda": "special-sweets",
  "spl-soan-papdi": "special-sweets",
  "spl-sweet-mix": "special-sweets",
  "spl-halwa": "special-sweets",

  // 🔹 Cakes
  "barbie-cake": "cakes",
  "birthday-vanilla-cake": "cakes",
  "birthday-flavours": "cakes",
  "birthday-fondant-cake": "cakes",
  "birthday-ice-cake-flavours": "cakes",
  "birthday-pastry": "cakes",
  "birthday-prime-ice-cake-flavours": "cakes",
  "birthday-prime-flavours": "cakes",
  "brownie-cake": "cakes",
  "butter-cream-eggless-cake": "cakes",
  "butter-cream-red-velvet": "cakes",
  "butter-scotch-cake": "cakes",
  "cake-desing": "cakes",
  "cake-drawing": "cakes",
  "cake-jar-90": "cakes",
  "cake-iopper": "cakes",
  "choco-truffle": "cakes",
  "chocolate-cake": "cakes",
  "cream-cake": "cakes",
  "customized-red-velvet-cake": "cakes",
  "customized-pastry": "cakes",
  "customized-eggless-cake": "cakes",
  "customized-eggless-cake-ice-cream": "cakes",
  "customized-flavour-cake": "cakes",
  "customized-ice-cake-flavours": "cakes",
  "customized-prime-flavours": "cakes",
  "customized-prime-ice-cake": "cakes",
  "customized-vanilla": "cakes",
  "dry-fruits": "cakes",
  "eclairs": "cakes",
  "eggless-cup-cake": "cakes",
  "fruits": "cakes",
  "honey-cake": "cakes",
  "ice-cake": "cakes",
  "mini-cheese-cake": "cakes",
  "mini-eclairs": "cakes",
  "pastry-red-velvet-cake": "cakes",
  "photo-print-cake": "cakes",
  "saffron-cake": "cakes",
  "spl-butter-cream-cake": "cakes",

  // 🔹 Cookies
  "butter-biscuits": "cookies",
  "salt-biscuits": "cookies",
  "cashew-biscuits": "cookies",

  // 🔹 Festival Specials
  "jangiri": "festivalspecials",
  "koppuram": "festivalspecials",
  "laadu-big": "festivalspecials",
  "nippat": "festivalspecials",
  "puffed-rice-ball": "festivalspecials",
  "round-murukku": "festivalspecials",
  "sweet-mix": "festivalspecials",

  // 🔹 Regular Sweets
  "bengali-sweets": "regularsweets",
  "bombay-halwa": "regularsweets",
  "boost-burfi": "regularsweets",
  "chandrakala": "regularsweets",
  "coconut-burfi": "regularsweets",
  "horlicks-burfi": "regularsweets",
  "halwa": "regularsweets",
  "jelabi": "regularsweets",
  "mini-badusha": "regularsweets",
  "mysorepak": "regularsweets",
  "peanut-burfi": "regularsweets",
  "peda": "regularsweets",
  "rava-laddo": "regularsweets",
  "soan-papdi": "regularsweets",
  "sweet-boondhi": "regularsweets",
  "thirupathi-laadu": "regularsweets",
  "till-barfi": "regularsweets",

  // 🔹 Savouries
  "finger-chips": "savories",
  "avalakki": "savories",
  "avara-mix-dal": "savories",
  "benne-murukku": "savories",
  "berigai-mixture": "savories",
  "bitter-gourd-pakoda": "savories",
  "bombay-mixture": "savories",
  "chana-dal-mix": "savories",
  "chettinadu-murukku": "savories",
  "chips": "savories",
  "congress": "savories",
  "corn-chips": "savories",
  "curry-murukku": "savories",
  "garlic-nippat": "savories",
  "jangiri-murukku": "savories",
  "kara-boondhi": "savories",
  "mangalore-mixture": "savories",
  "masala-badam": "savories",
  "masala-cashew": "savories",
  "masala-groundnuts": "savories",
  "masala-pori": "savories",
  "mix-mixtue": "savories",
  "mix-murukku": "savories",
  "moong-dal": "savories",
  "mota-sev": "savories",
  "om-podi": "savories",
  "pakoda": "savories",
  "pearl-pakoda": "savories",
  "regular-mixture": "savories",
  "regular-nippat": "savories",
  "ribbon-murukku": "savories",
  "rings": "savories",
  "special-murukku": "savories",
  "sweet-biscuit": "savories",
  "suthal-murukku": "savories",
  "till-murukku": "savories",
  "wheel-chips": "savories",

  // 🔹 Snacks
  "kachori": "snacks",
  "bread-chilly": "snacks",
  "bread-toast": "snacks",
  "burger": "snacks",
  "cheese-balls": "snacks",
  "chocolate-cream-bun": "snacks",
  "chutney-powders/paste": "snacks",
  "cold-coffee": "snacks",
  "cream-bun": "snacks",
  "dilpasand": "snacks",
  "dough-nut": "snacks",
  "egg-puff": "snacks",
  "fruit-cream-bun": "snacks",
  "jam-bun": "snacks",
  "jamoon": "snacks",
  "kara-bun": "snacks",
  "maddur-vada": "snacks",
  "mal-pua": "snacks",
  "masala-bun": "snacks",
  "mix-cake-and-pakoda": "snacks",
  "moos-cup": "snacks",
  "paneer-puff": "snacks",
  "pizza": "snacks",
  "popcorn": "snacks",
  "rasagulla": "snacks",
  "rasamalai-/-malaikulla": "snacks",
  "samosa": "snacks",
  "shahi-roll": "snacks",
  "snb-dairy-milk": "snacks",
  "snb-lollipop": "snacks",
  "spl-dilpasand": "snacks",
  "spl-dough-nut": "snacks",
  "veg-puff": "snacks",
  "veg-roll": "snacks",
  "veg-sandwich": "snacks"
};

export default itemCategoryMap;
